//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Repositorys.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Room Room { get; set; }
        public virtual Section Section { get; set; }
        public virtual User User { get; set; }
    }
}
